jbosstools/jbosstools-build-sites

- aggregate/site/category.xml
Include tern into aggregated jbosstools p2 repository
> [JBIDE-19185] Update tern.java to latest release 0.8.0.201501272018

- aggregate/component-site/pom.xml
- aggregate/pom.xml
> prepare for Final

- aggregate/pom.xml
- aggregate/site/pom.xml
remove ununsed results profile
> remove ununsed results profile

- aggregate/pom.xml
tweak readme in aggregate/pom.xml
> tweak readme in aggregate/pom.xml

- aggregate/pom.xml
> fake change #6

- aggregate/central-site/pom.xml
- aggregate/coretests-site/pom.xml
- aggregate/earlyaccess-site/pom.xml
- aggregate/pom.xml
- aggregate/site/pom.xml
> upversion to 4.4.1 / AM1

- aggregate/coretests-site/category.xml
- aggregate/site/category.xml
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> [JBIDE-25136] - Add OSIO related bundles/features to update site

- aggregate/coretests-site/category.xml
- aggregate/site/category.xml
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
> added new feature syndesis extensions

- aggregate/coretests-site/category.xml
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
> fixed some missing .source entries and added a IT bundle

- aggregate/site/category.xml
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> [JBIDE-26337] - org.jboss.tools.common.launcher.feature not included

- aggregate/site/category.xml
- Remove Central easymport feature
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> JBIDE-26650: Fix builds for TP based on 2019-06.M3

- aggregate/site/category.xml
- aggregate/site/pom.xml
> JBIDE-26863: added quarkus to aggregated core update site

- aggregate/site/category.xml
> JBIDE-26863: added source feature to the aggregated site.

- aggregate/site/category.xml
> JBIDE-26912: Remove Code Recommenders from the TP

- aggregate/site/category.xml
> JBIDE-27303: fix build

- aggregate/site/category.xml
> JBIDE-27296: update docker client

- aggregate/site/category.xml
> JBIDE-27372 : removed yedit from Target Platform

- aggregate/site/category.xml
> JBIDE-27533: add microprofile support in product

- aggregate/coretests-site/category.xml
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-27636 Add quarkus.test feature to coretests

- aggregate/coretests-site/pom.xml
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-27636 Add quarkus site in coretests pom

- aggregate/site/category.xml
> JBIDE-27832: fix missing source feature in aggregated site.

- aggregate/coretests-site/pom.xml
- aggregate/pom.xml
> JBIDE-26888 : Replace http access to https

- aggregate/site/category.xml
> JBIDE-28369: move m2e-apt to central

- aggregate/site/category.xml
> JBIDE-28442: adding cdi faces to aggregate
